name: test

on: [push, pull_request]

jobs:
    test:
        strategy:
          matrix:
            go-version: ['>=1.18.0']
            os: [ubuntu-latest,]
        runs-on: ${{ matrix.os }}
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Unshallow git checkout
          run:  git fetch --prune --unshallow
        - name: Run tests
          run: go test -v -covermode=count -coverprofile=coverage.out ./...
        - name: Convert coverage to lcov
          uses: jandelgado/gcov2lcov-action@v1.0.5
        - name: Report coverage
          uses: coverallsapp/github-action@master
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              path-to-lcov: coverage.lcov
        - name: Check lint
          run: |
              go get -u golang.org/x/lint/golint
              golint  ./...
    test-integration:
        strategy:
          matrix:
            go-version: ['>=1.18.0']
            os: [ubuntu-latest,]
        runs-on: ${{ matrix.os }}
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_HOST: localhost
                    POSTGRES_USER: test
                    POSTGRES_PASSWORD: test
                    POSTGRES_DB: test
                ports:
                    - 5445:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Unshallow git checkout
          run:  git fetch --prune --unshallow
        - name: Run tests
          run: go test -v -covermode=count -coverprofile=coverage.out ./...
        - name: Convert coverage to lcov
          uses: jandelgado/gcov2lcov-action@v1.0.5
        - name: Report coverage
          uses: coverallsapp/github-action@master
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              path-to-lcov: coverage.lcov
        - name: Check lint
          run: |
              cd tests/
              go test -v -count=1 -cover -covermode=count -coverprofile=coverage.out ./...
    doc:
        name: Refresh documentation
        runs-on: ubuntu-latest
        steps:
        - name: Pull new module version
          run: go install github.com/josuebrunel/clausify
          env:
            GOPROXY: https://proxy.golang.org
            GO111MODULE: on

